### ISSUE TITLE
Superclass method not found

### ISSUE THREAD

**Issue by jeff9finger** [sdaschner/jaxrs-analyzer#22] opened 2015-06-19 01:44 UTC
It seems that parsing the classes directory is not working as expected.
I am running on Yosemite with Java 8
$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

$ java -jar /Users/jeff/.m2/repository/com/sebastian-daschner/jaxrs-analyzer/0.5/jaxrs-analyzer-0.5.jar -b asciidoc -n TRACT -v 1.28 -d my.tractbilling.com -X target/classes
Exception in thread "main" java.lang.NullPointerException
	at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.addDirectoryClasses(ProjectAnalyzer.java:149)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.addDirectoryClasses(ProjectAnalyzer.java:151)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.addDirectoryClasses(ProjectAnalyzer.java:151)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.addProjectPath(ProjectAnalyzer.java:113)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer$$Lambda$17/1368884364.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer.analyze(ProjectAnalyzer.java:73)
	at com.sebastian_daschner.jaxrs_analyzer.JAXRSAnalyzer.analyze(JAXRSAnalyzer.java:69)
	at com.sebastian_daschner.jaxrs_analyzer.Main.main(Main.java:131)

**Comment by okoeth** [comment] 2015-06-19 06:52
Similar issue here. Worked two weeks ago when I last tried...
Caused by: java.lang.NullPointerException
        at com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo$$Lambda
$7/1628289406.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:
193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:
193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterat
ors.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)

        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.ja
va:502)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java
:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499
)
        at com.sebastian_daschner.jaxrs_analyzer.maven.JAXRSAnalyzerMojo.execute
(JAXRSAnalyzerMojo.java:107)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:132)
        ... 20 more

**Comment by sdaschner** [comment] 2015-06-19 09:42
@jeff9finger Confirmed. This is because of the relative classes directory (your `target/classes`). It works with absolute paths... Will fix this, as soon as I'm back from Devoxx :-) 

@okoeth Are you using the 0.5 version? Could you please provide more information of your Maven execution (e.g. parts of the Maven output started with the `-X` debug flag).

These two seem to be different issues.

Thanks!

**Comment by okoeth** [comment] 2015-06-19 10:49
Dear Sebastian, I was using 0.4. Now upgraded to 0.5, however error prevails. I shared the log via email as it includes quite some detail of my system ;-)

**Comment by jeff9finger** [comment] 2015-06-19 15:27
Thanks for the response. I was getting NPE in maven as well. I may have had a corrupted jar file or something. I have performed the maven build again with -U (and deleted the .m2/repository files before) and now get the following error:
`
INFO] analyzing JAX-RS resources, using Swagger backend
[DEBUG] Dependency paths are: [/Users/jeff/.m2/repository/com/transverse/bleep/bleep-domain-saas/1.28.2-SNAPSHOT/bleep-domain-saas-1.28.2-SNAPSHOT.jar, /Users/jeff/.m2/repository/org/springframework/spring-tx/3.1.1.RELEASE/spring-tx-3.1.1.RELEASE.jar, /Users/jeff/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar, /Users/jeff/.m2/repository/org/springframework/security/spring-security-core/3.1.0.RELEASE/spring-security-core-3.1.0.RELEASE.jar, /Users/jeff/.m2/repository/org/mockito/mockito-all/1.8.5/mockito-all-1.8.5.jar, /Users/jeff/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar, /Users/jeff/.m2/repository/org/apache/cxf/cxf-testutils/2.7.6/cxf-testutils-2.7.6.jar, /Users/jeff/.m2/repository/com/transverse/bleep/bleep-service/1.28.2-SNAPSHOT/bleep-service-1.28.2-SNAPSHOT.jar, /Users/jeff/.m2/repository/org/apache/cxf/cxf-rt-transports-http-jetty/2.7.6/cxf-rt-transports-http-jetty-2.7.6.jar, /Users/jeff/.m2/repository/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar, /Users/jeff/.m2/repository/org/springframework/spring-test/3.1.1.RELEASE/spring-test-3.1.1.RELEASE.jar, /Users/jeff/.m2/repository/com/transverse/bleep/bleep-domain/1.28.2-SNAPSHOT/bleep-domain-1.28.2-SNAPSHOT.jar, /Users/jeff/.m2/repository/org/springframework/spring-context-support/3.1.1.RELEASE/spring-context-support-3.1.1.RELEASE.jar, /Users/jeff/.m2/repository/org/springframework/spring-aop/3.1.1.RELEASE/spring-aop-3.1.1.RELEASE.jar, /Users/jeff/.m2/repository/org/apache/cxf/cxf-bundle-jaxrs/2.7.6/cxf-bundle-jaxrs-2.7.6.jar]
[DEBUG] Project paths are: [/Users/jeff/Workspaces/Tract/trunk-1.28.x/tract-projects/tract/bleep-api/target/classes]
[ERROR] Could not interpret project method: {className='com.transverse.bleep.api.rest.dto.accounting.adjustment.AdjustmentReasonRestService', methodName='getByParameter', returnType='com.transverse.bleep.api.dto.DTOObject', staticMethod='false', parameterTypes=[com.transverse.bleep.api.dto.EntityType, java.lang.String, java.lang.String]}
[DEBUG] javassist.NotFoundException: getByParameter(..) is not found in com.transverse.bleep.api.rest.dto.accounting.adjustment.AdjustmentReasonRestService
        at javassist.CtClassType.getDeclaredMethod(CtClassType.java:1229)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodContentAnalyzer.getRelevantInstructions(MethodContentAnalyzer.java:145)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodContentAnalyzer.addProjectMethods(MethodContentAnalyzer.java:104)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodContentAnalyzer.findProjectMethods(MethodContentAnalyzer.java:86)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.ResourceMethodContentAnalyzer.analyze(ResourceMethodContentAnalyzer.java:62)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodAnalyzer.analyzeMethodContent(MethodAnalyzer.java:239)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodAnalyzer.analyzeInternal(MethodAnalyzer.java:157)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.methods.MethodAnalyzer.analyze(MethodAnalyzer.java:77)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.classes.ClassAnalyzer$$Lambda$126/1147196620.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.classes.ClassAnalyzer.analyzeInternal(ClassAnalyzer.java:120)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.project.classes.ClassAnalyzer.analyze(ClassAnalyzer.java:64)
        at com.sebastian_daschner.jaxrs_analyzer.analysis.ProjectAnalyzer$$Lambda$18/1764619264.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
`

I get this error on what looks like every jaxrs annotated class in the project. All stacktraces seem to indicate a problem at MethodContentAnalyzer.getRelevantInstructions(MethodContentAnalyzer.java:145

I can provide more details if needed, but it looks like some sort of Reflection issue.

**Comment by sdaschner** [comment] 2015-06-23 05:55
@jeff9finger Now this is a different error. Seems like the Javassist framework can not load the `AdjustmentReasonRestService#getByParameter(EntityType, String, String)` method.
Could you please provide some information of that piece?
Are this method and the callers in separate projects?
Is the method called on a class or interface?
Could you maybe paste some sources (how the definitions of the contained classes and methods - both the callers and called - look like)?

@okoeth Answered by mail.

Thanks :-)

**Comment by sdaschner** [comment] 2015-07-05 06:34
FYI: the NPEs are fixed in the `0.6` version.

**Comment by jeff9finger** [comment] 2015-07-13 17:02
AdjustmentReasonRestService class is a subclass of BaseRestService which has the implementation of getByParameter. So it seems that javaassist is not able to find a method that is implemented in a superclass.

* All classes are in the same maven project.
* All methods are on classes (some abstract, some not). No interfaces are used.

public class BaseRestService {
...
protected final T getByParameter(EntityType entityType, String paramName, String paramValue) throws Exception {...}
...
}

public class RestService extends BaseRestService { ... }

public class AdjustmentReasonRestService extends RestService {
...
	@GET
	@Produces(MediaType.APPLICATION_XML)
	public AdjustmentReasonDTO getReason(@PathParam("eid") String eid) {
        ...
        return getByParameter(EntityType.AdjustmentReason, "eid", eid);
        }
...
}

EntityType is an enum.

BTW. The 0.6 version seemed to get past this problem, but I now get a java.lang.StackOverflowError. 
Exception in thread "main" java.lang.StackOverflowError
	at java.util.Vector.<init>(Vector.java:148)
	at java.util.Vector.<init>(Vector.java:157)
	at java.util.Stack.<init>(Stack.java:53)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.<init>(MethodSimulator.java:45)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.InjectableArgumentMethodSimulator.<init>(InjectableArgumentMethodSimulator.java:33)
	at com.sebastian_daschner.jaxrs_analyzer.model.methods.ProjectMethod.invoke(ProjectMethod.java:47)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulateInvoke(MethodSimulator.java:177)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulate(MethodSimulator.java:94)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator$$Lambda$199/975239896.accept(Unknown Source)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulateInternal(MethodSimulator.java:74)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.InjectableArgumentMethodSimulator.simulate(InjectableArgumentMethodSimulator.java:50)
	at com.sebastian_daschner.jaxrs_analyzer.model.methods.ProjectMethod.invoke(ProjectMethod.java:47)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulateInvoke(MethodSimulator.java:177)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulate(MethodSimulator.java:94)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator$$Lambda$199/975239896.accept(Unknown Source)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.MethodSimulator.simulateInternal(MethodSimulator.java:74)
	at com.sebastian_daschner.jaxrs_analyzer.analysis.bytecode.simulation.InjectableArgumentMethodSimulator.simulate(InjectableArgumentMethodSimulator.java

Will open a new issue for this.

**Comment by sdaschner** [comment] 2015-07-14 05:23
Ok, thanks!
I already know, what's the problem here ...

**Comment by sdaschner** [comment] 2015-08-14 14:49
Fixed in f2b7f52 and included in the latest `0.7` version.

**Closed by sdaschner** 2015-08-14 14:49 UTC
